services:
  podgist:
    image: ghcr.io/hddq/podgist:latest
    volumes:
      - ./data:/app/data:z
      - ./config.yaml:/app/config.yaml:z,ro
      - ./prompt.md:/app/prompt.md:z,ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1