services:
  podcast-summarizer:
    build: .
    image: podcast-summarizer_podcast-summarizer
    volumes:
      - ./downloads:/app/downloads:z
      - ./transcripts:/app/transcripts:z
      - ./models:/app/models:z
      - ./summaries:/app/summaries:z
      - ./state.json:/app/state.json:z
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1